#ifndef UTILS_H
#define UTILS_H

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>

#define GAME_TITLE "Flappy Bird"
#define SCREEN_WIDTH 432.0f
#define SCREEN_HEIGHT 768.0f
#define WINDOW_FLAG 0u
#define FPS 60
#define FRAME_TIME 1000.0f / FPS

#define BACKGROUND_PIXEL_WIDTH  144
#define BACKGROUND_PIXEL_HEIGHT 256

#define GROUND_PIXEL_WIDTH  168
#define GROUND_PIXEL_HEIGHT 56

#define BIRD_PIXEL_WIDTH  17
#define BIRD_PIXEL_HEIGHT 12

#define OBSTACLE_PIXEL_WIDTH  26
#define OBSTACLE_PIXEL_HEIGHT 160

#define IMAGE_SCALE SCREEN_WIDTH / BACKGROUND_PIXEL_WIDTH

#define GAP 160

#endif // !UTILS_H
