#ifndef UTILS_H
#define UTILS_H

#define GAME_TITLE "Flappy Bird"
#define SCREEN_WIDTH 400.0f
#define SCREEN_HEIGHT 700.0f
#define FULLSCREEN_MODE false
#define FPS 60
#define FRAME_TIME 1000.0f / FPS

#define BACKGROUND_PIXEL_WIDTH  144
#define BACKGROUND_PIXEL_HEIGHT 256

#define GROUND_PIXEL_WIDTH  168
#define GROUND_PIXEL_HEIGHT 56

#define BIRD_PIXEL_WIDTH  17
#define BIRD_PIXEL_HEIGHT 12

#define OBSTACLE_PIXEL_WIDTH  26
#define OBSTACLE_PIXEL_HEIGHT 160

#define IMAGE_SCALE 2 * 1.6f

#endif // !UTILS_H
